import java.util.HashMap;

public class ComidasNota {
	public HashMap<String,Float> notasComidas = new HashMap<String,Float>();
	public ComidasNota() {
		notasComidas.put("italian",10.0f);
		notasComidas.put("brazilian",9.9f);
		notasComidas.put("burger",9.8f);
		notasComidas.put("argentine",9.7f);
		notasComidas.put("bbq",9.6f);
		notasComidas.put("mexican",9.5f);
		notasComidas.put("japanese",9.4f);
		notasComidas.put("modern australian",9.3f);
		notasComidas.put("chinese",9.2f);
		notasComidas.put("turkish",9.1f);
		notasComidas.put("greek",9.0f);
		notasComidas.put("seafood",8.9f);
		notasComidas.put("fast food",8.8f);
		notasComidas.put("bar food",8.7f);
		notasComidas.put("pub food",8.6f);
		notasComidas.put("canadian",8.5f);
		notasComidas.put("german",8.4f);
		notasComidas.put("steak",8.3f);
		notasComidas.put("pizza",8.2f);
		notasComidas.put("teriyaki",8.1f);
		notasComidas.put("thai",8.0f);
		notasComidas.put("coffee and tea",7.9f);
		notasComidas.put("finger food",7.8f);
		notasComidas.put("bakery",7.7f);
		notasComidas.put("american",7.6f);
		notasComidas.put("cafe",7.5f);
		notasComidas.put("persian",7.4f);
		notasComidas.put("sushi",7.3f);
		notasComidas.put("deli",7.2f);
		notasComidas.put("sandwich",7.1f);
		notasComidas.put("soul food",7.0f);
		notasComidas.put("breakfast",6.9f);
		notasComidas.put("cajun",6.8f);
		notasComidas.put("australian",6.7f);	
		notasComidas.put("middle eastern",6.6f);
		notasComidas.put("tapas",6.5f);
		notasComidas.put("european",6.4f);
		notasComidas.put("vietnamese",6.3f);
		notasComidas.put("korean",6.2f);
		notasComidas.put("cantonese",6.1f);
		notasComidas.put("malay",6.0f);
		notasComidas.put("singaporean",5.9f);
		notasComidas.put("spanish",5.8f);
		notasComidas.put("tex-mex",5.7f);
		notasComidas.put("asian",5.6f);
		notasComidas.put("british",5.5f);
		notasComidas.put("irish",5.4f);
		notasComidas.put("diner",5.3f);
		notasComidas.put("latin american",5.2f);
		notasComidas.put("continental",5.1f);
		notasComidas.put("southern",5.0f);
		notasComidas.put("desserts",4.9f);
		notasComidas.put("western",4.8f);
		notasComidas.put("mediterranean",4.7f);
		notasComidas.put("new american",4.6f);
		notasComidas.put("french",4.5f);
		notasComidas.put("cuban",4.4f);
		notasComidas.put("hawaiian",4.3f);
		notasComidas.put("ice cream",4.2f);
		notasComidas.put("beverages",4.1f);
		notasComidas.put("southwestern",4.0f);
		notasComidas.put("dim sum",3.9f);
		notasComidas.put("international",3.8f);
		notasComidas.put("caribbean",3.7f);
		notasComidas.put("salad",3.6f);
		notasComidas.put("tea",3.5f);
		notasComidas.put("bubble tea",3.4f);
		notasComidas.put("indian",3.2f);
		notasComidas.put("vegetarian",3.1f);		
	}
}
